// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnN-6_10FdYI_r588jhOSRxB1jZq0CF1Y',
    appId: '1:250098409902:web:797884e450e464c81da83f',
    messagingSenderId: '250098409902',
    projectId: 'worthit-58ab4',
    authDomain: 'worthit-58ab4.firebaseapp.com',
    storageBucket: 'worthit-58ab4.firebasestorage.app',
    measurementId: 'G-GZB1RWJTYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCouV3iA6EoRzreSVPNLcZt08AM7s1FFuA',
    appId: '1:250098409902:android:8f94f25ea13a1f6e1da83f',
    messagingSenderId: '250098409902',
    projectId: 'worthit-58ab4',
    storageBucket: 'worthit-58ab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAhy1fa4Y0ry6vqgkJuxykxLUBSV3vmGY',
    appId: '1:250098409902:ios:7c3def60310a12851da83f',
    messagingSenderId: '250098409902',
    projectId: 'worthit-58ab4',
    storageBucket: 'worthit-58ab4.firebasestorage.app',
    iosClientId: '250098409902-vhicd33pg4dk6i39elmev71avnp0t015.apps.googleusercontent.com',
    iosBundleId: 'com.example.worthitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAhy1fa4Y0ry6vqgkJuxykxLUBSV3vmGY',
    appId: '1:250098409902:ios:7c3def60310a12851da83f',
    messagingSenderId: '250098409902',
    projectId: 'worthit-58ab4',
    storageBucket: 'worthit-58ab4.firebasestorage.app',
    iosClientId: '250098409902-vhicd33pg4dk6i39elmev71avnp0t015.apps.googleusercontent.com',
    iosBundleId: 'com.example.worthitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnN-6_10FdYI_r588jhOSRxB1jZq0CF1Y',
    appId: '1:250098409902:web:28eeaeb0625895891da83f',
    messagingSenderId: '250098409902',
    projectId: 'worthit-58ab4',
    authDomain: 'worthit-58ab4.firebaseapp.com',
    storageBucket: 'worthit-58ab4.firebasestorage.app',
    measurementId: 'G-E72GDFHP5Y',
  );

}